spring.application.name=back

# BD embarquée HSQLDB en fichier (pas besoin de serveur externe)
spring.datasource.url=jdbc:hsqldb:file:${user.home}/facade-db/${spring.application.name};shutdown=true
spring.datasource.driverClassName=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Dialecte Hibernate pour HSQLDB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HSQLDialect

# Afficher les requêtes SQL (debug — comme dans le TP3)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

