spring.application.name=back

# DB (simple) : HSQLDB en fichier pour garder les joueurs entre redémarrages
spring.datasource.url=jdbc:hsqldb:file:${user.home}/facade-db/${spring.application.name};shutdown=true
spring.datasource.username=sa
spring.datasource.password=

# JPA : crée/maj le schéma automatiquement (TP)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
